// Fotos reais do acervo — obras já fotografadas em ambiente (ver images/acervo/)
window.OBRAS_FOTOS = [
  { n: 1, file: 'obra-01.jpeg' },
  { n: 2, file: 'obra-02.jpeg' },
  { n: 3, file: 'obra-03.jpeg' },
  { n: 4, file: 'obra-04.jpeg' },
  { n: 5, file: 'obra-05.jpeg' },
  { n: 6, file: 'obra-06.jpeg' },
  { n: 7, file: 'obra-07.jpeg' },
  { n: 8, file: 'obra-08.jpeg' },
  { n: 9, file: 'obra-09.jpeg' },
  { n: 10, file: 'obra-10.jpeg' },
  { n: 11, file: 'obra-11.jpeg' },
  { n: 12, file: 'obra-12.jpeg' },
  { n: 13, file: 'obra-13.jpeg' },
  { n: 14, file: 'obra-14.jpeg' },
  { n: 15, file: 'obra-15.jpeg' },
  { n: 16, file: 'obra-16.jpeg' },
  { n: 17, file: 'obra-17.jpeg' },
  { n: 18, file: 'obra-18.jpeg' },
  { n: 19, file: 'obra-19.jpeg' },
  { n: 20, file: 'obra-20.jpeg' },
  { n: 21, file: 'obra-21.jpeg' },
  { n: 22, file: 'obra-22.jpeg' },
  { n: 23, file: 'obra-23.jpeg' },
  { n: 24, file: 'obra-24.jpeg' },
  { n: 25, file: 'obra-25.jpeg' },
  { n: 26, file: 'obra-26.jpeg' },
  { n: 27, file: 'obra-27.jpeg' },
  { n: 28, file: 'obra-28.jpeg' },
  { n: 29, file: 'obra-29.jpeg' },
  { n: 30, file: 'obra-30.jpeg' },
  { n: 31, file: 'obra-31.jpeg' },
  { n: 32, file: 'obra-32.jpeg' },
  { n: 33, file: 'obra-33.jpeg' },
  { n: 34, file: 'obra-34.jpeg' },
  { n: 35, file: 'obra-35.jpeg' },
];
